### ISSUE TITLE
Using "react-gluejar" from "npm i" gives different API

### ISSUE THREAD

**Issue by fmaiabatista** [charliewilco/react-gluejar#3]
Hi, Charlie,

I just installed your lib via `npm i react-gluejar` because I don't use yarn and `npm i @charliewilco/react-gluejar` was returning errors.

First thing I noticed is that instead of a destructured import `import { Gluejar } from "@charliewilco/react-gluejar"` I had to make a default import `import Gluejar from "react-gluejar"`.

In addition to that, first time I copied your example it gave me exception "Cannot read length of undefined" because `images` were not defined. I had to debug the internals of the `react-gluejar/dist/index.js` to find that the component was calling the children function passing an `items` argument instead of `{ images }`.

So, to make it work, I had to have the final code:
```
<Gluejar
    onPaste={files => console.log(files)}
    onError={err => console.error(err)}
>
    {items => {
        if (items && items.length > 0) {
            return items.map(item => (
                <img src={item} key={item} alt={`Pasted: ${item}`} />
            ));
        }
         return null;
    }}
</Gluejar>
```

Is that intended or the example has to be updated to reflect the lastest API available?

**Comment by charliewilco** [comment]
hi @fmaiabatista! `react-gluejar` was the first version of this that i never took down from NPM.

you can totally just use `npm install @charliewilco/gluejar`. sorry for the confusion.

**Comment by knikhilvshetty** [comment]
what are the dependence to close image div.Can you please help me out
